version: '2'
services:
  postgres:
    build:
      context: .\database
      dockerfile: Dockerfile
    ports:
    - 2345:5432
    environment:
      POSTGRES_PASSWORD: password
  scrapper:
    build:
      context: .\
      dockerfile: Dockerfile


